name: CI/CD Configuration of the Node

on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version :'18.18.1'
      - name: Install the node
        run: npm install
      - name: Build the Node file
        run: npm run build --if-present
      - name: Test the file
        run: npm test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SECRETE_NAME }}
          password: ${{ secrets.SECRETE_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jeeva10/nodeapplication:latest
          
